apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-single-git-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NaveenBalagouni/my-single-git-app.git'
    targetRevision: main
    path: single-git-source
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: naveen
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
