apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
    path: single-git-source
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: naveen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
