apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: double-helm-charts-app
  namespace: argocd
spec:
  destination:
    namespace: double-helm
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
      path: my-helm-charts/single-helm-resources
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
      path: my-helm-chart-resources/single-helm-resource
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
