apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: double-helm-charts-app
  namespace: argocd
spec:
  destination:
    namespace: double-helm
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/OpsMx/argo-sample-apps.git'
      path: apps-resources/single-helm-resource
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/OpsMx/argo-sample-apps.git'
      path: apps-resources/double-helm-resource
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
  project: qa-environment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
