apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: list-applicationset-first-application
            repoURL: https://github.com/NaveenBalagouni/my-argo-practice.git          #pod
            targetRevision: main
            path: Generator-resources/list-generator-resource/app1
          - name: list-applicationset-second-application
            repoURL: https://github.com/NaveenBalagouni/my-argo-practice.git           #service
            targetRevision: main
            path: Generator-resources/list-generator-resource/app2
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
