apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-git-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: naveen
  sources:
    - repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
      path: two-git-sources/git-sources
      targetRevision: main
    - repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
      path: two-git-sources/two-git
      targetRevision: main
