apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-git-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: naveen
  sources:
    - repoURL: https://github.com/NaveenBalagouni/my-argo-practice.git
      path: two-git-sources/git-sources
      targetRevision: test
    - repoURL: https://github.com/NaveenBalagouni/my-argo-practice.git
      path: datas/git/two-git-source/git2
      targetRevision: test
