apiVersion: argoproj.io/v1alpha1
kind: Applications
metadata:
  name: sample-multiple-sources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
        revision: HEAD
        directories:
          - path: two-git-sources/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
