# This YAML defines an Argo CD ApplicationSet named sample-multiple-sources, which automates the creation of multiple Argo CD applications from specified directories within a Git repository. It generates applications based on the contents of the two-git-sources/git-sources and two-git-sources/two-git paths, allowing each application to be deployed to the Kubernetes cluster in the applicationsets namespace
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-multiple-sources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
        revision: HEAD
        directories:
          - path: two-git-sources/git-sources
          - path: two-git-sources/two-git
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NaveenBalagouni/my-argo-practice.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: applicationsets
