apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset-ui
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - repoURL: 'https://github.com/OpsMx/argo-sample-apps.git'
            targetRevision: HEAD
            path: apps-resources/single-helm-resource
            helm:
              valueFiles:
                - values.yaml
    - clusters:
        selector:
          matchLabels:
            environment: qa
    - git:
        repoURL: 'https://github.com/OpsMx/argo-sample-apps.git'
        revision: main
        directories:
          - path: apps-resources/double-helm-resource
  template:
    metadata:
      name: test-app-ui-{{name}}
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{helm.valueFiles}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - CreateNamespace=true
