# YAML defines a Kubernetes ConfigMap named game-demo, which stores configuration settings for a game application. It includes simple key-value pairs such as the initial number of player lives and the name of the UI properties file, as well as file-like keys containing game-specific properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: 
    color.good=purple
    color.bad=yellow
    allow.textmode=true
